### ISSUE TITLE
Roadmap for 0.3.0 Release

### ISSUE THREAD

**Issue by sikersten** [pyfar/pyfar#238]
## General

* pyfar version: 0.2.3

Topics to be finished for v0.3.0 release
- [x] Handling fft normalizations, #224, #235 + implementations
- [x] separate concepts in documentation, #228
- [x] read/write audio #234 
- [x] convolution/deconvolution #232, #212
- [x] Finalize filter classes, #102, #36, #204
- [x] Read sofa files using sofar
- [x] Review Contributing.rst
- [x] Verbose Filter names #170 
- [x] check documentation for consistency
- [x] Check deprecation warnings noted by pytest
- [x] Check fft_norms for signals provided by pyfar.signals
