### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#267]
0.5.0 - deadline for reviews is 15. September, release 1. October

New pulls won't be included in the next release.

- [x] Resample
- [x] Fractional Delay
- [x] Fractional Smoothing
- [x] Minimum phase refactoring
- [x] Decibel
- [x] Audio files #315 (ready to merge)
- [x] Find delay and start of impulse response
- [x] Matrix multiplication #277 (ready to merge)
- [x] Update arithmetic docstrings, #320
- [x] Auditory filter bank
- [x] Normalize #323  (depends on #338, needs minor changes & merge from develop)
- [x] Averaging #330 (open questions)
- [x] Energy/RMS/Power calculation #338 (merge conflict with develop)
- [x] Read comsol #339 (requires #344 ?)
- [x] soundfile update, mp3 support #361, #365
- [x] Update History

For later
- [ ] Soft limiting #325 
- [ ] Frequency domain sweep synthesis #199
