### ISSUE TITLE
We need to implement calculations of commonly used constants

### ISSUE THREAD

**Issue by mberz** [pyfar/pyfar#428]
We need an implementation to calculate and store typically used constants, such as air density, speed of sound, etc.
Ideally, this could be implemented as a Dataclass or similar.

**Comment by sikersten** [comment]
Let's start a list to get an overview :)

**Comment by ahms5** [comment]
yes sure: 
- [ ] air_attenualion (according to the standard #734)
- [ ] speed of sound simple based on temperature (#732)
- [ ] speed of sound ideal gas law, based on temperature, humidity, pressure (needs the saturation_vapor_pressure in #734) 
- [ ] speed of sound cramer method, based on temperature, humidity, pressure, and co2 concentration (Cramer, Owen, The variation of the specific heat ratio and the speed 
      of sound in air with temperature, pressure, humidity, and CO2 
      concentration. J. Acoust. Soc. Am. 1 May 1993; 93 (5): 
      2510–2516. https://doi.org/10.1121/1.405827)
- [ ] documentation of different methods

all the missing prs are already drafted in here #503 
having all methods in separate methods makes it much easier to use and to maintain. Its strait forward, what parameter is used in the calculation and which not.
we can discuss tomorrow.

**Comment by ahms5** [comment]
We decided to reject the idea of a class for the speed of sound calculation, because requirements for the methods differ between the methods. so we decided to go for independed methods for each calcualtion method

**Comment by ahms5** [comment]
- [ ] we also add a method to calculate the density of air https://github.com/pyfar/pyfar/pull/774

**Comment by ahms5** [comment]
already merged in dev
