### ISSUE TITLE
Ruff configuration

### ISSUE THREAD

**Issue by mberz** [pyfar/pyfar#647]
Currently ruff is set-up to replicate the flake8 guidelines, which could be extended.
I'm creating this issue to keep track of the different configuration options and respective branches.

In progress:
- [ ] docstring rules #612 and #685
- [ ] pytest rules #692 
- [x] "FIX": Code should not contain FIXME, TODO, etc. #687 
- [x] "ERA": No commented out code #686
- [x] "NPY": Check all numpy related deprecations #688 
- [x] "COM": trailing comma rules. Can be very helpful to avoid accidental tuple creation and other problems. - COM819?  #689 
- [x] "A": Avoid builtin function and type shadowing. #690
- [x] "I002": [missing-required-import](https://docs.astral.sh/ruff/rules/missing-required-import/)  #691
- [x] "TID252": Use absolute over relative imports.  #691
- [x] "ARG": Remove unused function/method arguments. #697
- [ ] "B": flake8-bugbear extension. Contains a number of guidelines (seem to be quite opinionated, but at least some look very reasonable) https://docs.astral.sh/ruff/rules/#flake8-bugbear-b  - without B006, B008 #698
- [x] "C4": flake8-comprehensions #699 

Some of them are very easy to apply and already mostly fulfilled in pyfar. For example, builtin shadowing was something we tried to avoid (although not 100% successful as it seems :) )
Some may even be auto-fixed., others require more changes and additional care. 
Feel free to suggest additional rules or rules (or respective subsets) which should not be enforced.

Update: We agreed on all options except for "B" and will discuss options from @ahms5 at a later point but want to have "C90" and "C4" and "PT011" mentioned in #613 (as a separate pull)

**Comment by ahms5** [comment]
note on in progress:
- [ ] docstring rules https://github.com/pyfar/pyfar/pull/612
```
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D106", # Missing docstring in public nested class
```
- [ ] also docstring https://github.com/pyfar/pyfar/pull/614
```
    "D206", # Docstring should be indented with spaces, not tabs
    "D207", # Docstring is under-indented
    "D208", # Docstring is over-indented
    "D407", # Missing section underline
    "D408", # Section underline should be in the line following the section's name
    "D409", # Section underline should match the length of its name
    "D410", # Missing blank line after section
    "D411", # Missing blank line before section
    "D412", # No blank lines allowed between a section and its content
    "D414", # Section has no content
    "D419", # Docstring is empty
```

and i would also add the the discussion:
- "ARG" check for unused arguments in functions methods, classes, etc
- "C4" flake8-comprehensions 
- "I" sort import, might be good to also uniform our imports and make them properly
- "C90"  [Checks for functions with a high McCabe complexity.](https://docs.astral.sh/ruff/rules/complex-structure/)
- "N" naming conventions (maybe a subset)

**Comment by ahms5** [comment]
we decided to add the following rules:

In progress:
- [ ] docstring rules #614 #612, add D415, D417
- [ ] pytest rules #613 
- [ ] "FIX": Code should not contain FIXME, TODO, etc.
- [ ] "ERA": No commented out code
- [ ] "NPY": Check all numpy related deprecations
- [ ] "COM": trailing comma rules. Can be very helpful to avoid accidental tuple creation and other problems. - COM819? 
- [ ] "A": Avoid builtin function and type shadowing.
- [ ] "I002": [missing-required-import](https://docs.astral.sh/ruff/rules/missing-required-import/)
- [ ] "TID252": Use absolute over relative imports.
- [ ] "ARG": Remove unused function/method arguments.
- [ ] "B": flake8-bugbear extension. Contains a number of guidelines (seem to be quite opinionated, but at least some look very reasonable) https://docs.astral.sh/ruff/rules/#flake8-bugbear-b  - without B006, B008
- [ ] "C4": flake8-comprehensions

**Comment by ahms5** [comment]
i guess its done
